### ISSUE TITLE
default=false, not working?

### ISSUE THREAD

**Issue by Techn1x** [canufeel/ember-leaflet-layer-control#12]
Perhaps I don't understand correctly, but shouldn't `default=false` not show the layer group on the map by default? Essentially I would like the group to be in the layer control, but be unchecked by default, and this doesn't seem to do anything.

```handlebars
{{#layer-group name="Track" default=false}}
...
{{/layer-group}}
```

If I'm not understanding correctly, what does the flag actually do? And is it possible to not show a layer by default somehow?

Thanks!

**Comment by Techn1x** [comment]
I've come back to this issue and it seems as though the `default` flag only works for base layers (setting to true makes it the selected base layer), whereas for native leaflet layers (eg polylines) setting to false or removing the attribute doesn't seem to do anything - the "Track" layer remains selected/checked/displayed by default.

```handlebars
{{#layer-group name="Track" default=false}}
  {{polyline-layer locations=(message-location-array (await mainTrack))}}
  {{polyline-decorator latlngs=(message-location-array (await mainTrack)) patterns=currentLinePatterns}}
{{/layer-group}}
```

**Comment by Techn1x** [comment]
This is fixed by https://github.com/canufeel/ember-leaflet-layer-control/pull/10

When using that PR code, the default=false on overlay layers will in fact not show them by default

**Comment by canufeel** [comment]
@Techn1x ok, closing
