### ISSUE TITLE
default parameter in template declaration doesn't work

### ISSUE THREAD

**Issue by zion** [canufeel/ember-leaflet-layer-control#14]
If I have this inside `{{#leaflet-map}}` the layer is still enabled on page/map load
```
{{#layer-group name="Road segment" default=false}}
    {{polyline-layer locations=polylineLocations color="red"}}
{{/layer-group}}
```

**Comment by zion** [comment]
Ok, so apparently, v0.2.0 on npm: https://www.npmjs.com/package/ember-leaflet-layer-control is behind master. 

So anyone that does `ember install ember-leaflet-layer-control` is getting a broken addon from the beginning. 

This issue is actually fixed in master I think.

Can we get a new release tag for npm?

**Comment by Techn1x** [comment]
I had the same issue and is one reason why my webapp is pointing to master for this addon.. made an issue here, hopefully we get a version published https://github.com/canufeel/ember-leaflet-layer-control/issues/19

**Comment by Techn1x** [comment]
Latest v0.2.1 released should now fix this, if OP confirms

**Comment by zion** [comment]
Yes, much better. Thank you!
