### ISSUE TITLE
Ember leaflet 3.0.2 breaks ember-leaflet-layer-control

### ISSUE THREAD

**Issue by ashleysommer** [canufeel/ember-leaflet-layer-control#2]
Need to replace `ember-leaflet/mixins/container` with `ember-composability-tools`
https://github.com/miguelcobain/ember-leaflet/commit/25ea9bb6f4cbbc84768c73150ff2a1e0c0dbe9aa

**Comment by zbeat** [comment]
+1

**Comment by bugduino** [comment]
+1
