### ISSUE TITLE
Adding/removing layer-groups dynamically

### ISSUE THREAD

**Issue by Techn1x** [canufeel/ember-leaflet-layer-control#8]
Hello,

I've been trying to display a layer-group on a map, when I have the tracking data for it. I would also like to only show the layer-control for the group when this data comes in (**itemLocations** is no longer null). The way I thought it would be done would be something like this;

```handlebars
{{#if itemLocations}}
	{{#layer-group name="24 hour track" default=true}}
			{{!-- Track --}}
			{{polyline-layer locations=itemLocations color="blue"}}
			
			{{!-- Marker at each tracking point --}}
			{{#each itemLocations as |loc|}}
				{{#circle-marker-layer location=loc radius=1}}
				{{/circle-marker-layer}}
			{{/each}}
	{{/layer-group}}
{{/if}}
```

Before the data comes in (itemLocations is null) everything is displayed correctly (layer isn't on map yet and no control in the layer-control). When the data is available and itemLocations is an array of locations, the data is drawn correctly on the map, but the layer control option for the group is missing, it's as if the layer-control wasn't updated or something.

Is this the correct approach? Is this even possible to do with this addon? Do I need to invalidate/refresh the layer-control or something to get it to update the available layer-group options?

Thanks for your help

**Comment by canufeel** [comment]
Hey! Adding and removing layers dynamically is not really supported by this addon. Layer registration is only done once when the template is first rendered hence the requirement to respect component ordering (`layer-group` should go before `layer-control`) There is a way to do it in Leaflet itself - http://leafletjs.com/reference-1.0.3.html#control-layers via `addBaseLayer` and `addOverlay`. There seems to be 2 possible approaches to implement it. You can either implement some synthetic event to trigger one of the layers and to get a reference for leaflet map - 

```
{
    layer: ##the layer which was triggered##,
    name: ##layer name as set on layer group##,
    overlay: ##true/false##,
    target: ##Leaflet map object##,
    type: ##"overlayadd"/"overlayremove"/"baselayerchange"##
}
``` 

consider `target` prop here. And then use its `addOverlay` etc. methods to update the layers. This one is really quick and dirty.

But that is not proper approach. Proper one would be to add ability to observe amount of layers registered from inside of this addon and perform updates when they change. Currently i don't really use this addon much and i don't even have application which uses it. So PR's are very welcome to extend the functionality.

**Comment by Techn1x** [comment]
Thanks for the response :) I will look into how I might implement a solution like this and potentially make a PR. In the meantime - how trivial do you think it would be to implement an attribute on the layer-group (say enableControl=true/false) that just puts a disabled attribute on the layer-control element for that layer-group so that it can't be toggled? How would I go about doing this?

**Comment by canufeel** [comment]
Not sure they can be enabled/disabled that way. Have a look at the code anyway: https://github.com/canufeel/ember-leaflet-layer-control/blob/master/addon/components/layer-group.js#L19:L40 Here `layer-group` registers itself on `leaflet-map` component by adding its `layer` to one of the arrays - either `_baseLayers` or `_layerGroups`. This happens before any layer groups are initialised with `Leaflet.map` object. After all layers have been registered this way `layer-control` component does the following: https://github.com/canufeel/ember-leaflet-layer-control/blob/master/addon/components/layer-control.js#L21:L40 Here it just goes through array of collected layers and registers them with `Leaflet.map`object which is sitting in `leaflet-map` component of `ember-leaflet`. Good luck in your research 😄
